services:
  postgres:
    image: postgres
    volumes:
      - ./postgres_db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./postgres_db/seeder_db.sql:/docker-entrypoint-initdb.d/seeder_db.sql
    environment:
      POSTGRES_PASSWORD: "senha123"
    ports:
      - "5432:5432"
    container_name: db-pg

  backend:
    depends_on:
      - postgres
    image: node_api
    build:
      dockerfile: ./node_api/dockerfile
    ports:
      - "3010:3010"
    command:
      [
        "sh",
        "-c",
        "dockerize -wait tcp://db-pg:5432 -timeout 60s && node node_api/app.js",
      ]

  frontend:
    depends_on:
      - backend
    image: react_app
    build:
      dockerfile: ./react_app/dockerfile
    ports:
      - "3000:3000"
    command: ["sh", "-c", "cd ./react_app && npm run start"]
